// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edge.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Edge.pbobjc.h"
#import "Result.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - EdgeRoot

@implementation EdgeRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[ResultRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - EdgeRoot_FileDescriptor

static GPBFileDescriptor *EdgeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"common"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PEdgeVersion

@implementation PEdgeVersion

@dynamic forceUpdate;
@dynamic recommendUpdate;
@dynamic updateInAppStore;
@dynamic latestVersion;
@dynamic updateLink;

typedef struct PEdgeVersion__storage_ {
  uint32_t _has_storage_[1];
  BOOL forceUpdate;
  BOOL recommendUpdate;
  BOOL updateInAppStore;
  NSString *latestVersion;
  NSString *updateLink;
} PEdgeVersion__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "forceUpdate",
        .number = PEdgeVersion_FieldNumber_ForceUpdate,
        .hasIndex = 0,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(PEdgeVersion__storage_, forceUpdate),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "recommendUpdate",
        .number = PEdgeVersion_FieldNumber_RecommendUpdate,
        .hasIndex = 1,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(PEdgeVersion__storage_, recommendUpdate),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "updateInAppStore",
        .number = PEdgeVersion_FieldNumber_UpdateInAppStore,
        .hasIndex = 2,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
        .offset = offsetof(PEdgeVersion__storage_, updateInAppStore),
        .defaultValue.valueBool = NO,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "latestVersion",
        .number = PEdgeVersion_FieldNumber_LatestVersion,
        .hasIndex = 3,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
        .offset = offsetof(PEdgeVersion__storage_, latestVersion),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "updateLink",
        .number = PEdgeVersion_FieldNumber_UpdateLink,
        .hasIndex = 4,
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
        .offset = offsetof(PEdgeVersion__storage_, updateLink),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\005\001K\000\002O\000\003P\000\004M\000\005J\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PEdgeVersion class]
                                     rootClass:[EdgeRoot class]
                                          file:EdgeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(PEdgeVersion__storage_)
                                    wireFormat:NO
                           extraTextFormatInfo:extraTextFormatInfo];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
