// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PaymentRoot

@interface PaymentRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PWeixinPay

typedef GPB_ENUM(PWeixinPay_FieldNumber) {
  PWeixinPay_FieldNumber_Appid = 1,
  PWeixinPay_FieldNumber_Partnerid = 2,
  PWeixinPay_FieldNumber_Noncestr = 3,
  PWeixinPay_FieldNumber_Timestamp = 4,
  PWeixinPay_FieldNumber_Prepayid = 5,
  PWeixinPay_FieldNumber_Package = 6,
  PWeixinPay_FieldNumber_Sign = 7,
  PWeixinPay_FieldNumber_OrderNo = 8,
};

@interface PWeixinPay : GPBMessage

// 应用ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *appid;

// 商户号
@property(nonatomic, readwrite, copy, null_resettable) NSString *partnerid;

// 随机串
@property(nonatomic, readwrite, copy, null_resettable) NSString *noncestr;

// 时间戳
@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;

// 预支付串
@property(nonatomic, readwrite, copy, null_resettable) NSString *prepayid;

// 订单信息串
@property(nonatomic, readwrite, copy, null_resettable) NSString *package;

// 签名串
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

// 订单的编号
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNo;

@end

#pragma mark - PAlipayOrderInfo

typedef GPB_ENUM(PAlipayOrderInfo_FieldNumber) {
  PAlipayOrderInfo_FieldNumber_OrderNo = 1,
  PAlipayOrderInfo_FieldNumber_PayInfo = 2,
};

// 生成订单的编号和订单的签名信息
@interface PAlipayOrderInfo : GPBMessage

// 订单的编号
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNo;

// 订单的签名信息
@property(nonatomic, readwrite, copy, null_resettable) NSString *payInfo;

@end

#pragma mark - PPayOrderList

typedef GPB_ENUM(PPayOrderList_FieldNumber) {
  PPayOrderList_FieldNumber_PayOrdersArray = 1,
};

@interface PPayOrderList : GPBMessage

// 支付订单信息
// |payOrdersArray| contains |PPayOrder|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *payOrdersArray;
@property(nonatomic, readonly) NSUInteger payOrdersArray_Count;

@end

#pragma mark - PPayOrder

typedef GPB_ENUM(PPayOrder_FieldNumber) {
  PPayOrder_FieldNumber_OrderNo = 1,
  PPayOrder_FieldNumber_PayType = 2,
  PPayOrder_FieldNumber_OrderSubject = 3,
  PPayOrder_FieldNumber_OrderBody = 4,
  PPayOrder_FieldNumber_Amount = 5,
  PPayOrder_FieldNumber_PayTime = 6,
  PPayOrder_FieldNumber_PayStatu = 7,
  PPayOrder_FieldNumber_BankType = 8,
  PPayOrder_FieldNumber_TotalFee = 9,
  PPayOrder_FieldNumber_ErrCodeDes = 10,
  PPayOrder_FieldNumber_EndTime = 11,
};

@interface PPayOrder : GPBMessage

// 订单的编号
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderNo;

// 支付渠道（WX-微信,ZFB-支付宝）
@property(nonatomic, readwrite, copy, null_resettable) NSString *payType;

// 商品名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderSubject;

// 商品描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderBody;

// 预支付金额（单位：分）
@property(nonatomic, readwrite) int64_t amount;

// 发起支付时间
@property(nonatomic, readwrite) int64_t payTime;

// 支付状态， 0-支付中，1-支付成功，2-支付失败 ， 当pay_statu=1或2时，有以下数据
@property(nonatomic, readwrite) int32_t payStatu;

// 付款银行
@property(nonatomic, readwrite, copy, null_resettable) NSString *bankType;

// 实际支付金额（单位：分）
@property(nonatomic, readwrite) int64_t totalFee;

// 支付失败原因描述
@property(nonatomic, readwrite, copy, null_resettable) NSString *errCodeDes;

// 支付完成时间
@property(nonatomic, readwrite) int64_t endTime;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
