// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: social.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class PUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SocialRoot

@interface SocialRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PFriendCount

typedef GPB_ENUM(PFriendCount_FieldNumber) {
  PFriendCount_FieldNumber_Count = 1,
};

@interface PFriendCount : GPBMessage

// 好友数量
@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - PSearchUser

typedef GPB_ENUM(PSearchUser_FieldNumber) {
  PSearchUser_FieldNumber_IsFriend = 1,
  PSearchUser_FieldNumber_IsFollowing = 2,
  PSearchUser_FieldNumber_User = 7,
};

// 搜索用户信息
@interface PSearchUser : GPBMessage

// 是否已经是好友
@property(nonatomic, readwrite) BOOL isFriend;

// 是否已经申请好友
@property(nonatomic, readwrite) BOOL isFollowing;

//保留3~6用于扩展
@property(nonatomic, readwrite) BOOL hasUser;
@property(nonatomic, readwrite, strong, null_resettable) PUser *user;

@end

#pragma mark - PSearchUserList

typedef GPB_ENUM(PSearchUserList_FieldNumber) {
  PSearchUserList_FieldNumber_SearchUsersArray = 1,
};

// 搜索用户返回列表
@interface PSearchUserList : GPBMessage

// |searchUsersArray| contains |PSearchUser|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *searchUsersArray;
@property(nonatomic, readonly) NSUInteger searchUsersArray_Count;

@end

#pragma mark - PIsFriendList

typedef GPB_ENUM(PIsFriendList_FieldNumber) {
  PIsFriendList_FieldNumber_IsFriendArray = 1,
};

// 是否是好友信息列表
@interface PIsFriendList : GPBMessage

// 是否是好友
@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *isFriendArray;
@property(nonatomic, readonly) NSUInteger isFriendArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
